// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRuRteKCqFJR4l6SpU_NphDKuoV8Ag01k',
    appId: '1:730140148453:web:46ff7ce0af11e148ea8a0c',
    messagingSenderId: '730140148453',
    projectId: 'gallery-app-rishitha',
    authDomain: 'gallery-app-rishitha.firebaseapp.com',
    storageBucket: 'gallery-app-rishitha.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqtJvcWe5YuwNetm5c3ujy6cc0oSwTch0',
    appId: '1:730140148453:android:c346cd46364ef760ea8a0c',
    messagingSenderId: '730140148453',
    projectId: 'gallery-app-rishitha',
    storageBucket: 'gallery-app-rishitha.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqdGTlNuio85VmiuuMxTSHOxcwCmqkANk',
    appId: '1:730140148453:ios:5a885211ed56d3d7ea8a0c',
    messagingSenderId: '730140148453',
    projectId: 'gallery-app-rishitha',
    storageBucket: 'gallery-app-rishitha.firebasestorage.app',
    androidClientId: '730140148453-nv61iqg8kni1t6mosseaifg1v771r3ej.apps.googleusercontent.com',
    iosClientId: '730140148453-sbkk1tuncih5mvq5niifqbd7q35kitr4.apps.googleusercontent.com',
    iosBundleId: 'com.example.gallery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqdGTlNuio85VmiuuMxTSHOxcwCmqkANk',
    appId: '1:730140148453:ios:5a885211ed56d3d7ea8a0c',
    messagingSenderId: '730140148453',
    projectId: 'gallery-app-rishitha',
    storageBucket: 'gallery-app-rishitha.firebasestorage.app',
    androidClientId: '730140148453-nv61iqg8kni1t6mosseaifg1v771r3ej.apps.googleusercontent.com',
    iosClientId: '730140148453-sbkk1tuncih5mvq5niifqbd7q35kitr4.apps.googleusercontent.com',
    iosBundleId: 'com.example.gallery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRuRteKCqFJR4l6SpU_NphDKuoV8Ag01k',
    appId: '1:730140148453:web:e1274e72389f605eea8a0c',
    messagingSenderId: '730140148453',
    projectId: 'gallery-app-rishitha',
    authDomain: 'gallery-app-rishitha.firebaseapp.com',
    storageBucket: 'gallery-app-rishitha.firebasestorage.app',
  );

}